add curve fitting statistics
Sjoerd1993/Graphs pull request #501
Opened 2023-09-15 12:27 UTC by Sjoerd1993

Adds some statistics to the curve fitting data, and shows bounds for the confidence interval (based on one standard deviation). Also rounds the given data to three significant digits. 

 For goodness of fit it shows an R2 value. Note that this assumes no intrinsic errors in the y-data that is given in, so it's a measure of how good the model fits to the data, not of the uncertainty of the data itself. Which I believe is why the measure is somewhat controversial, nevertheless it can be useful information imo.

Still need to add options to turn the bounds off, and show different kind of confidence intervals if reasonably possible, but thinking of doing that in a different PR. See picture:

![image](https://github.com/Sjoerd1993/Graphs/assets/68477016/cf1b22ab-187f-4ef7-b4ab-ac1cffa03b93)

2023-09-15 13:17 UTC, cmkohnen approved these changes

2023-09-15 15:24 UTC, Sjoerd1993 commented
There was an issue with the latest PR, mainly that the old bounds were not removed when redrawing new ones. The other issue is that the canvas limits would not update. The limits are bound to the figure settings. Hence those being used now. As the autoscale is basically overwritten in the canvas implementation, a logic similar to optimize_limits is being used here.

In the move to Vala, there were two things that I did not get working:
1 - The binding of the AdwEntryRow to the values in settings. For some reason, the `Tools.bind_settings_to_widgets` would correctly get the key, but did not retrieve any widgets. Hence assigning self.equation so I could use the python variant.
2 - The binding of the button to the Python call to add_fit. Hence the binding in the code here.

The latest commit fixes this. A bit more logic has been moved into Vala as well.

2023-09-15 16:10 UTC, cmkohnen requested changes
Again, I feel like Figure Settings aren't needed here, we don't really need labels, scales are set to linear anyways and the limits can be set using just the canvas. I doesn't need to be tied to another class, as this only introduces overhead.

2023-09-15 17:02 UTC, Sjoerd1993 commented
> Again, I feel like Figure Settings aren't needed here, we don't really need labels, scales are set to linear anyways and the limits can be set using just the canvas. I doesn't need to be tied to another class, as this only introduces overhead.

The problem is that the limits are not properly applied, but I think I found the culprit actually, which seems to lie in the autoscale setting. For some reason, even though the PolyCollection object is removed (the one that contains the confidence bounds), it still keeps the highest limits as reference. Turning off autoscale makes it work quite well without needing figure settings. Am working on a fixing that, will see if I have time for that today. I'll toggle a re-review when I've got a cleaner solution here. As I agree that we should avoid figure settings here, especially if it's just to set one single property (limits). At the time it seemed like it was the only way to set the limits though, as those were stuck (when autoscale was turned on).

2023-09-17 11:00 UTC, cmkohnen approved these changes

2023-09-17 11:13 UTC, merged