Refactor
Sjoerd1993/Graphs pull request #504
Opened 2023-09-17 13:47 UTC by cmkohnen

- Integrate view clipboard and data clipboard into data
- Integrate optimize limits into data
- change project keys

2023-09-17 19:30 UTC, Sjoerd1993 requested changes
I'll try and look into this into a bit more detail tomorrow, when I have time but some quick things I noticed:

- Performing a redo doesn't change the limits back to the position it was at that stage.
- Optimize limits from the action menu is broken: `TypeError: Data.optimize_limits() takes 1 positional argument but 2 were given`

See video, showing some more bugs.

[Screencast from 2023-09-17 21-29-04.webm](https://github.com/Sjoerd1993/Graphs/assets/68477016/50d830d6-9611-4de8-84bc-3f42e2b14672)

2023-09-17 19:30 UTC, Sjoerd1993 commented on src/actions.py
> +    if data.props.view_back_possible:
Just a suggestion, but perhaps `data.props.can_view_back` would make sense? It's a bit shorter, and has the same meaning in the end.

2023-09-17 19:30 UTC, Sjoerd1993 commented on src/ui.py
> +        item_list.append(ItemBox(self, item, count))
The `count` variable sets the index for the new item to be added, right? Wouldn't it make sense to call it index then?

2023-09-17 20:27 UTC, cmkohnen commented
Mentioned bugs should be fixed, some were actually introduced earlier, but just arose now

2023-09-18 08:28 UTC, Sjoerd1993 approved these changes
I think the migration from clipboard, figure settings and optimize limits make sense in the context of the new curve fitting tool. While working on that, I noticed there were multiple aspects that had a too strong coupling with the main application. 

This refactor makes it all a lot more versatile. Even though Data is becoming quite big as a class.

2023-09-18 08:28 UTC, Sjoerd1993 commented on src/data.py
> +    def _delete_item(self, key):
I was actually considering renaming this mehtod either way, as a `pop` action in Python also returns the item that is deleted. This method does not, so it's a bit of misleading name to call this pop.

2023-09-18 08:28 UTC, merged